import type { Metadata } from "next";
import "./globals.css";
import { jost } from "./fonts";


export const metadata: Metadata = {
  title: "Valete Plus - O Aplicativo que Reúne Conhecimento e Cultura em Um Só Lugar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={` w-screen overflow-x-hidden ${jost.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
